
CREATE TABLE Banks (
id INT(6) NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
address VARCHAR(30) NOT NULL,
email VARCHAR(50),
);

CREATE TABLE Users (
id INT(6) NOT NULL AUTO_INCREMENT,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(50),
);
